controllers:
    resource: ../src/Controller/
    type: attribute
app_answer:
    path: /answer/{answerId}
    controller: App\Controller\AnswerController::answer
    requirements:
        $answerId: '\d+'
